spring.application.name=protcar

server.port=5000

# Configurações do Banco de Dados PostgreSQL
spring.datasource.url=jdbc:postgresql://protcar-db.cbos6g4acayu.sa-east-1.rds.amazonaws.com:5432/postgres?sslmode=require
spring.datasource.username=postgres
spring.datasource.password=L7!qP9#vR2$xK8
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# Configurações de Segurança e JWT
api.security.token.secret=${JWT_SECRET:chave-secreta-protcar-2026}
admin.username=${ADMIN_USER:admin}
admin.password=${ADMIN_PASS:123456}